language: rust
sudo: false
rust:
- stable
- beta
- nightly
os:
- linux
matrix:
  include:
  - rust: stable
  - os: osx
  allow_failures:
  - os: osx
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  [ $TRAVIS_OS_NAME = linux ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  pip install --user ghp-import &&
   ~/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: PHh0o6XyVteMW6Z838gKatvFYbJCabzAZrLCH95lcSmmxv6UBW2JmAP/JsUbXv7opQ95MPqxEY9gR4p9acksEI0MQMucuPal5/2PAYdtIeupfIYqdKiGOclHLOtEmB5CKuYCuto58HCknHFCiXRtSNEZewXu19+fEDpdfJK/Pws=
