language: rust
sudo: required
rust:
- nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
after_success:
- travis-cargo --only nightly doc-upload
- travis-cargo coveralls
env:
  global:
    secure: Fku/OkesA90Z1QlnrqsmWCsUuOCTUzhOecmR2djCB4ppJmpELMFDwtVXmXrZmxvmbfePvM5vxb8gDlC80FgcX6q2ZC9rakielMCfE6x6BRSM4NivaOnLC+jB1GBt/SfR09enKuCrCQxQIoK0pSB2BImZeon72gANej0oyKL6Eiw=
