[package]

name = "substudy"
version = "0.0.1"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Tools for working with parallel, bilingual subtitles"
license = "Unlicense"

documentation = "http://www.rust-ci.org/emk/substudy/doc/substudy/"
repository = "https://github.com/emk/substudy"
readme = "README.md"
keywords = ["text"]

[dependencies]
docopt_macros = "~0.6.8"
encoding = "~0.2.3"
uchardet = "~0.0.6"
peg = "~0.1.0"

[[bin]]
name = "substudy"
test = false
doc = false
