[package]

name = "substudy"
version = "0.0.1"
authors = ["Eric Kidd <git@randomhacks.net>"]

[dependencies.peg]
#git = "https://github.com/kevinmehall/rust-peg.git"
# Temporary fixes:
git = "https://github.com/emk/rust-peg.git"
branch = "enum_scoping"

[dependencies.docopt_macros]
#git = "git://github.com/docopt/docopt.rs"
# Temporary fixes:
git = "git://github.com/CraZySacX/docopt.rs"

[dependencies.encoding]
git = "https://github.com/lifthrasiir/rust-encoding"

[dependencies.uchardet]
git = "git://github.com/emk/rust-uchardet"

[[bin]]
name = "substudy"
test = false
doc = false
