[package]

name = "substudy"
version = "0.0.5"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Tools for working with parallel, bilingual subtitles"
license = "Unlicense"

documentation = "http://www.rust-ci.org/emk/substudy/doc/substudy/"
repository = "https://github.com/emk/substudy"
readme = "README.md"
keywords = ["text"]

[features]
# Allow access to unstable features when being built with a nightly compiler,
# to keep travis-cargo happy and enable access to benchmarks if we want them.
unstable = []

[dependencies]
docopt = "*"
docopt_macros = "*"
encoding = "*"
uchardet = "*"
peg = "*"
rustc-serialize = "*"
regex = "*"
regex_macros = "*"
log = "*"

[[bin]]
name = "substudy"
test = false
doc = false
