[package]

name = "substudy"
version = "0.1.1"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Tools for working with parallel, bilingual subtitles"
license = "Unlicense"

documentation = "http://www.rust-ci.org/emk/substudy/doc/substudy/"
repository = "https://github.com/emk/substudy"
readme = "README.md"
keywords = ["text"]

[features]
default = ["video"]
# Enable this to build experimental video support.
video = []

[dependencies]
docopt = "0.6.76"
encoding = "0.2.32"
log = "0.3.3"
num = "0.1.28"
rustc-serialize = "0.3.16"
regex = "0.1.41"
uchardet = "1.0.0"

[[bin]]
name = "substudy"
test = false
doc = false
