[package]
name = "substudy-server"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

build = "build.rs"

[dependencies]
docopt = "0.6.76"
env_logger = "0.3.2"
iron = "0.2.5"
mount = "0.0.9"
rustc-serialize = "0.3.16"
rustless = "0.7.2"
staticfile = "0.0.6"
substudy = { path = ".." }
