(function() {var implementors = {};
implementors['regex_syntax'] = ["impl&lt;'a, 'b, T&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;&amp;'b <a class='struct' href='http://doc.rust-lang.org/nightly/collections/btree/set/struct.BTreeSet.html' title='collections::btree::set::BTreeSet'>BTreeSet</a>&lt;T&gt;&gt; for &amp;'a <a class='struct' href='http://doc.rust-lang.org/nightly/collections/btree/set/struct.BTreeSet.html' title='collections::btree::set::BTreeSet'>BTreeSet</a>&lt;T&gt;","impl&lt;E&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/collections/enum_set/struct.EnumSet.html' title='collections::enum_set::EnumSet'>EnumSet</a>&lt;E&gt;&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/collections/enum_set/struct.EnumSet.html' title='collections::enum_set::EnumSet'>EnumSet</a>&lt;E&gt;",];implementors['peg_syntax_ext'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/syntax/parse/parser/struct.Restrictions.html' title='syntax::parse::parser::Restrictions'>Restrictions</a>&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/syntax/parse/parser/struct.Restrictions.html' title='syntax::parse::parser::Restrictions'>Restrictions</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/syntax/codemap/struct.BytePos.html' title='syntax::codemap::BytePos'>BytePos</a>&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/syntax/codemap/struct.BytePos.html' title='syntax::codemap::BytePos'>BytePos</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/syntax/codemap/struct.CharPos.html' title='syntax::codemap::CharPos'>CharPos</a>&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/syntax/codemap/struct.CharPos.html' title='syntax::codemap::CharPos'>CharPos</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
